package com.neueda.leap.controllers;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.boot.info.BuildProperties;
import org.springframework.dao.DataAccessException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import java.util.HashMap;
import java.util.Map;

/**
 * Root API Controller - Information and Health Endpoints
 */
@RestController
@RequestMapping("")
@CrossOrigin(origins = "*")
@Tag(name = "API Info", description = "Root API information and health check endpoints")
public class ApiController {

    private final JdbcTemplate jdbcTemplate;
    private final String version;

    public ApiController(JdbcTemplate jdbcTemplate, ObjectProvider<BuildProperties> buildProperties) {
        this.jdbcTemplate = jdbcTemplate;
        // build-info.properties is generated by the spring-boot-maven-plugin's
        // build-info goal; it is absent when classes are run straight from the IDE.
        BuildProperties build = buildProperties.getIfAvailable();
        this.version = build != null ? build.getVersion() : "unknown";
    }

    /**
     * API Root Info
     * GET /api
     */
    @GetMapping
    @Operation(summary = "Get API Information", description = "Returns general information about the Leap Frogs Trading API: service name, build version, status, and links to the generated API documentation")
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "Successfully retrieved API info",
            content = @Content(mediaType = "application/json", examples = @ExampleObject(value = """
                    {"service":"Leap Frogs Trading API","version":"0.1.0","status":"UP",\
                    "documentation":"/api/swagger-ui.html","openapi":"/api/v3/api-docs"}"""))
        )
    })
    public Map<String, Object> apiInfo() {
        Map<String, Object> info = new HashMap<>();
        info.put("service", "Leap Frogs Trading API");
        info.put("version", version);
        info.put("status", "UP");
        // The endpoint list is not repeated here: it is generated from the actual
        // request mappings and served at the two links below.
        info.put("documentation", "/api/swagger-ui.html");
        info.put("openapi", "/api/v3/api-docs");
        return info;
    }

    /**
     * Health Check
     * GET /api/health
     */
    @GetMapping("/health")
    @Operation(summary = "Health Check", description = "Verifies the health status of the Leap Frogs API service and its dependencies")
    @ApiResponses(value = {
        @ApiResponse(
            responseCode = "200",
            description = "Service and database are healthy",
            content = @Content(mediaType = "application/json", examples = @ExampleObject(value = """
                    {"status":"UP","service":"Leap Frogs API","timestamp":1759320000000,"database":"UP"}"""))
        ),
        @ApiResponse(
            responseCode = "503",
            description = "Database is unreachable",
            content = @Content(mediaType = "application/json", examples = @ExampleObject(value = """
                    {"status":"DOWN","service":"Leap Frogs API","timestamp":1759320000000,"database":"DOWN"}"""))
        )
    })
    public ResponseEntity<Map<String, Object>> health() {
        boolean databaseUp = isDatabaseUp();

        Map<String, Object> health = new HashMap<>();
        health.put("status", databaseUp ? "UP" : "DOWN");
        health.put("service", "Leap Frogs API");
        health.put("timestamp", System.currentTimeMillis());
        health.put("database", databaseUp ? "UP" : "DOWN");

        HttpStatus httpStatus = databaseUp ? HttpStatus.OK : HttpStatus.SERVICE_UNAVAILABLE;
        return ResponseEntity.status(httpStatus).body(health);
    }

    private boolean isDatabaseUp() {
        try {
            jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            return true;
        } catch (DataAccessException e) {
            return false;
        }
    }
}
